datasources:
- name: 'prometheus'
  type: 'prometheus'
  access: 'proxy'
  org_id: 1
  url: 'http://prometheus:9090'
  is_default: true
  version: 1
  editable: true
- name: Loki
  type: loki
  access: proxy
  url: http://192.168.100.38:3100
  editable: true
  isDefault: true
- name: Jaeger
  type: jaeger
  access: browser
  url: http://192.168.100.38:16686
  editable: true
